### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by jrobinso** [mljs/levenberg-marquardt#49]
npm run build fails with the following error

```
sh: cheminfo-build: command not found
```

**Comment by jrobinso** [comment]
oops my mistake.  Closing.

**Comment by jrobinso** [comment]
It still fails, after npm install, with the following error.  Some instructions for building for a browser would be helpful

```
npm run build

> ml-levenberg-marquardt@4.1.0 build
> cheminfo-build

Building bundle...
Error: Could not resolve entry module (lib-esm/index.js).
    at error (.../levenberg-marquardt/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (.../levenberg-marquardt/node_modules/rollup/dist/shared/rollup.js:22482:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}

```

**Comment by jobo322** [comment]
Could try with `npm run tsc` before the build script

**Comment by jrobinso** [comment]
That worked, thanks.
